### ISSUE TITLE
problem on concatenate (coreml mode)

### ISSUE THREAD

**Issue by gengtsh** [dmlc/nnvm#182]
when i run my coreml mode on nnvm, I get an issue which may related to concatenate symbol. or maybe i do something wrong, please take a look at it. thanks in advance. 

Traceback (most recent call last):
  File "nnvm_coreml.py", line 43, in <module>
    sym, params = nnvm.frontend.from_coreml(mlmodel)
  File "nnvm/python/nnvm/frontend/coreml.py", line 369, in from_coreml
    coreml_op_to_nnvm(layerop, list(l.input), l.output[0], symtab)
  File "nnvm/python/nnvm/frontend/coreml.py", line 309, in coreml_op_to_nnvm
    ret = _convert_map[classname](op, insym, symtab)
  File "nnvm/python/nnvm/frontend/coreml.py", line 249, in ConcatLayerParams
    ret = _sym.concatenate(*insyms, dim=1)
  File "nnvm/python/nnvm/_ctypes/symbol.py", line 181, in creator
    ctypes.byref(sym_handle)))
  File "nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Cannot find argument 'dim', Possible Arguments:
----------------
axis : int, optional, default='1'
    the axis to be concated.
, in operator concatenate(name="", dim="1")

**Comment by tqchen** [comment]
@PENGUINLIONG can you submit a fix? The problem is that the concatenate's argument should be axis instead of dim

**Comment by PENGUINLIONG** [comment]
See #184

**Comment by gengtsh** [comment]
hello, i'm very sorry to bother again. right now, i encounter another problem:
Traceback (most recent call last):
  File "nnvm_coreml.py", line 63, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/nnvm/python/nnvm/compiler/build_module.py", line 237, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/nnvm/python/nnvm/top/nn.py", line 106, in compute_conv2d
    out = topi.nn.conv2d(inputs[0], inputs[1], strides, padding)
  File "<decorator-gen-27>", line 2, in conv2d
  File "/tvm/python/tvm/target.py", line 219, in dispatch_func
    return func(*args, **kwargs)
  File "/tvm/topi/python/topi/nn/conv2d.py", line 82, in conv2d
    return conv2d_nchw(data, kernel, stride, padding)
  File "/tvm/topi/python/topi/nn/conv2d.py", line 260, in conv2d_nchw
    batch, in_channel, in_height, in_width = Input.shape
ValueError: need more than 0 values to unpack

**Comment by PENGUINLIONG** [comment]
Seems like your input have a shape of... nothing? That's weird. It _should_ work properly because most DL software come up with convolution layer in the first place. It's rare they are not tested properly.

Could you provide a minimum script reproducing the error?

**Comment by gengtsh** [comment]
i use from_coreml.py (in tutorial model), the only change i made was using my coreml model. my original model is caffe, then i just coremltools transfer caffe model to coreml mode.

**Comment by tqchen** [comment]
close since original problem is resolved. Feel free to open another issue(would be helpful if you can provide a minimum script to reproduce the error)

**Comment by gengtsh** [comment]
no, the problem is not resolved... , just nobody reply me....
then i download squeezenet model from coreml model website, and i encounter the same issues:
Traceback (most recent call last):
  File "nnvm_coreml.py", line 63, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/nnvm/python/nnvm/compiler/build_module.py", line 237, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/nnvm/python/nnvm/top/nn.py", line 139, in compute_max_pool2d
    assert not ceil_mode, "not support ceil_mode now"
AssertionError: not support ceil_mode now

**Comment by tqchen** [comment]
That is another problem other than the original concatenate issue, so we could move to a separate issue here
